In [2]:
import os
import glob
import numpy as np
import json
from func import *
import pandas as pd

In [44]:
opt_folder_path = './data/cxr_opt_healthcheck_zfill3'
opt_user_name = ['u2_u11', 'u3_u12', 'u4_u13', 'u5_u14', 'u6_u15', 'u7_u16', 'u8_u17', 'u9_u18', 'u10_u19']
use_ais = ['without_AI', 'with_AI']

In [55]:
mapping_df = pd.read_csv('./data/brmh_2_mapping_table_healthcheck.csv')
mapping_cases = mapping_df['case_no'].tolist()

In [58]:
df = pd.DataFrame(columns = ['opt_user', 'case_name', 'seq','label_without', 'rate_without', 'label_with', 'rate_with'])

for i in range(len(opt_user_name)):
#     if i == 1:
#         break
#     i=5
    # without_AI
    print(opt_user_name[i], use_ais[0])
    opt_without_path = os.path.join(opt_folder_path,opt_user_name[i],use_ais[0])
    opt_without_json_li = glob.glob(opt_without_path+'/*.json')
    
    opt_with_path = os.path.join(opt_folder_path,opt_user_name[i],use_ais[1])
    opt_with_json_li = glob.glob(opt_with_path+'/*.json')

    for k in range(len(opt_without_json_li)):
        opt_without = opt_without_json_li[k]
        contours_opt_without, contourIds_without, rating_list_without, rate_without = json_opt_open(opt_without)
        name_without = opt_without[opt_without.rindex('\\')+1:-5].zfill(3)
        
        opt_with = opt_with_json_li[k]
        contours_opt_with, contourIds_with, rating_list_with, rate_with = json_opt_open(opt_with)
        name_with = opt_with[opt_with.rindex('\\')+1:-5].zfill(3)
        
        case_name = mapping_cases[int(name_without)-1]
        
        if name_with==name_without:
            if contours_opt_without:
                label_without = 1
            else:
                label_without = 0

            if contours_opt_with:
                label_with = 1
            else:
                label_with = 0
        else:
            print('no match')
        
#         print(opt_user_name[i], name_without, label_without, rate_without, label_with, rate_with)
        data = {'opt_user':opt_user_name[i], 'case_name':case_name, 'seq':name_without, 'label_without':label_without, 'rate_without':rate_without, 
                'label_with':label_with, 'rate_with':rate_with}
        
        df=df.append(data , ignore_index=True)

u2_u11 without_AI
u3_u12 without_AI
u4_u13 without_AI
u5_u14 without_AI
u6_u15 without_AI
u7_u16 without_AI
u8_u17 without_AI
u9_u18 without_AI
u10_u19 without_AI

In [59]:
df

     opt_user  case_name  seq label_without rate_without label_with rate_with
0      u2_u11  K-A2-0015  001             0            0          0         0
1      u2_u11  K-A2-0021  002             0            0          1         2
2      u2_u11  K-A2-0029  003             0            0          1         4
3      u2_u11  K-A2-0043  004             0            0          0         0
4      u2_u11  K-A2-0089  005             0            0          1         2
...       ...        ...  ...           ...          ...        ...       ...
4315  u10_u19  B-A2-1636  476             0            0          0         0
4316  u10_u19  B-A2-1658  477             0            0          0         0
4317  u10_u19  B-A2-1675  478             0            0          0         0
4318  u10_u19  B-A2-1677  479             1            2          1         3
4319  u10_u19  B-A2-1683  480             0            0          0         0

[4320 rows x 7 columns]

In [60]:
df.to_csv('opt_label.csv', index=False)